// Jeremy's IT Lab  -  CCNA 200-301 Full Course
// Each video: day, title, phase (1-5), youtube search URL, summary bullets, active recall questions

export const COURSE = [
  // ── PHASE 1: CONSOLIDATION (Days 1-15) ───────────────────────────────────
  { day:1, title:"Network Devices", phase:1, mins:28,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+1+network+devices",
    summary:["Routers connect different networks and route packets at Layer 3","Switches connect devices within a LAN using MAC addresses at Layer 2","Firewalls filter traffic between networks based on rules","Hubs are legacy Layer 1 devices that flood all traffic to all ports  -  replaced by switches","IDS monitors and alerts; IPS is inline and can block threats"],
    recall:["What layer does a router operate at and what does it use to make forwarding decisions?","What is the key difference between a hub and a switch?","Name three differences between IDS and IPS."]},
  { day:2, title:"Interfaces and Cables", phase:1, mins:34,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+2+interfaces+cables",
    summary:["UTP copper cables use RJ-45 connectors; max distance 100m for Ethernet","Straight-through cables connect different device types (PC->switch); crossover connects same types","Auto-MDIX allows modern devices to auto-detect cable type","Single-mode fibre supports longer distances (100km+); multi-mode supports up to ~550m","SFP transceivers allow fibre or copper modules to be inserted into switches"],
    recall:["What is the maximum cable length for 1000BASE-T?","When would you use a crossover cable vs straight-through?","What is auto-MDIX and why is it useful?"]},
  { day:3, title:"OSI Model & TCP/IP Suite", phase:1, mins:52,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+3+OSI+model",
    summary:["OSI has 7 layers; TCP/IP has 4. OSI is conceptual, TCP/IP is the real-world model","Layer 7=Application, 6=Presentation, 5=Session, 4=Transport, 3=Network, 2=Data Link, 1=Physical","PDUs: Segment (L4), Packet (L3), Frame (L2), Bits (L1)","Encapsulation adds headers at each layer going down; decapsulation removes them going up","Same-layer communication is logical; adjacent-layer is actual interaction on one device"],
    recall:["List the 7 OSI layers in order from top to bottom.","What is the PDU at Layer 3? Layer 2? Layer 4?","What is encapsulation and where does it happen?"]},
  { day:4, title:"Intro to the CLI", phase:1, mins:46,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+4+cisco+CLI",
    summary:["User EXEC mode (>) has limited commands; Privileged EXEC (#) has full access","Global config mode (config)# is used to make configuration changes","'enable secret' is encrypted; 'enable password' is plaintext  -  always use secret","'service password-encryption' encrypts existing plaintext passwords (Type 7, weak)","'do' prefix lets you run EXEC commands from config mode"],
    recall:["What command enters privileged EXEC mode from user EXEC?","What is the difference between 'enable password' and 'enable secret'?","How do you run a show command while in global config mode?"]},
  { day:5, title:"Ethernet LAN Switching Part 1", phase:1, mins:49,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+5+ethernet+LAN+switching",
    summary:["Switches build a MAC address table by reading the SOURCE MAC of incoming frames","Unknown unicast frames are flooded to all ports except the incoming port","Broadcast frames (FF:FF:FF:FF:FF:FF) are also flooded to all ports","Known unicast frames are forwarded only to the port associated with the destination MAC","MAC table entries age out (default 5 minutes) if no traffic is seen from that MAC"],
    recall:["How does a switch learn MAC addresses?","What happens when a switch receives a frame with an unknown destination MAC?","What is the difference between flooding and forwarding?"]},
  { day:6, title:"Ethernet LAN Switching Part 2", phase:1, mins:45,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+6+ethernet+LAN+switching+2",
    summary:["Ethernet frame: Preamble(7B)+SFD(1B)+Dst MAC(6B)+Src MAC(6B)+Type(2B)+Data+FCS(4B)","Minimum frame size is 64 bytes; max is 1518 bytes (without 802.1Q tag)","FCS (Frame Check Sequence) uses CRC to detect errors  -  frames with errors are dropped","Type field: 0x0800=IPv4, 0x0806=ARP, 0x86DD=IPv6","ARP maps IP addresses to MAC addresses  -  switch forwards ARP replies after learning MAC"],
    recall:["What are the fields in an Ethernet II frame in order?","What is the minimum and maximum Ethernet frame size?","What EtherType value indicates an IPv4 packet?"]},
  { day:7, title:"IPv4 Addressing Part 1", phase:1, mins:53,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+7+IPv4+addressing",
    summary:["IPv4 = 32-bit address written as 4 octets in dotted decimal notation","Network portion is identified by the subnet mask; host portion identifies the device","Class A: /8 default, Class B: /16, Class C: /24  -  classes are mostly legacy","Private ranges: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16","Loopback: 127.0.0.0/8  -  always points back to the local device"],
    recall:["What are the three private IP address ranges defined in RFC 1918?","What class is 172.20.0.0 and what is its default mask?","What is the purpose of the loopback address?"]},
  { day:8, title:"IPv4 Addressing Part 2", phase:1, mins:48,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+8+IPv4+addressing+2",
    summary:["Network address = first address in subnet (host bits all 0)  -  cannot be assigned","Broadcast address = last address (host bits all 1)  -  cannot be assigned","Usable hosts = 2^host_bits − 2","To find subnet: AND the IP with the subnet mask","Maximum hosts in a /24 = 254; in a /30 = 2"],
    recall:["How many usable hosts are in a /26 subnet?","Given IP 192.168.1.200/27, what is the subnet address and broadcast?","What is the formula for calculating number of usable hosts?"]},
  { day:9, title:"Switch Interfaces", phase:1, mins:41,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+9+switch+interfaces",
    summary:["'show interfaces status' shows port status, VLAN, duplex, speed, type","Full-duplex: simultaneous send/receive; half-duplex: one direction at a time","Duplex mismatch causes late collisions and poor performance  -  hard-set on critical links","Auto-negotiation should be used consistently  -  both sides or neither","err-disabled state occurs after violations (port security, BPDU guard, etc.)"],
    recall:["What command shows all switch interface statuses in a compact table?","What causes late collisions on an Ethernet link?","What does err-disabled mean and how do you recover from it?"]},
  { day:10, title:"IPv4 Header", phase:1, mins:38,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+10+IPv4+header",
    summary:["IPv4 header is 20-60 bytes; key fields: Version, IHL, DSCP, Total Length, TTL, Protocol, Src/Dst IP","TTL: decremented by 1 at each router; when 0, packet dropped and ICMP Time Exceeded sent","Protocol field: 6=TCP, 17=UDP, 1=ICMP, 89=OSPF","DSCP (6 bits) used for QoS marking  -  replaces old IP Precedence","Fragmentation: MF flag and Fragment Offset allow large packets to be split"],
    recall:["What happens when a packet's TTL reaches 0?","What protocol number identifies TCP? UDP? OSPF?","What is the purpose of the DSCP field in the IPv4 header?"]},
  { day:11, title:"Routing Fundamentals Part 1", phase:1, mins:44,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+11+routing+fundamentals",
    summary:["Routing table populated by: connected, static, and dynamic routing protocols","Longest prefix match wins when multiple routes match a destination","Connected routes (AD=0) added automatically when interface is configured with IP and up/up","Static routes (AD=1) configured manually with 'ip route network mask next-hop'","Default route 0.0.0.0/0 matches all destinations  -  used when no more specific route exists"],
    recall:["What is longest prefix match? Give an example.","What is the administrative distance of a connected route? A static route?","What command configures a default route on a Cisco router?"]},
  { day:12, title:"Routing Fundamentals Part 2", phase:1, mins:39,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+12+routing+fundamentals+2",
    summary:["'show ip route' shows the full routing table; letter codes indicate source (C=connected, S=static, O=OSPF)","Route via next-hop: router must be able to reach the next-hop IP","Route via exit interface: works but can cause ARP issues on Ethernet (use both for precision)","Recursive routing: router looks up next-hop in routing table to find exit interface","Gateway of last resort is the default route displayed in routing table output"],
    recall:["What does the 'O' code mean in 'show ip route' output?","What is recursive routing?","What is the Gateway of Last Resort?"]},
  { day:13, title:"Subnetting Part 1", phase:1, mins:56,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+13+subnetting",
    summary:["Subnetting divides a network into smaller subnets by borrowing bits from the host portion","Number of subnets = 2^borrowed_bits; hosts per subnet = 2^remaining_host_bits − 2","Block size = 256 − subnet mask interesting octet; subnets increment by block size","/24 network divided into /26 gives 4 subnets of 62 hosts each","Always identify: network address, broadcast address, first and last usable host"],
    recall:["How many subnets and hosts does a /27 create from a /24?","What is the block size of a /26 subnet?","For 192.168.1.0/26, list all subnets, their network and broadcast addresses."]},
  { day:14, title:"Subnetting Part 2", phase:1, mins:51,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+14+subnetting+2",
    summary:["VLSM = Variable Length Subnet Masking  -  allocate differently-sized subnets from one block","Always allocate largest subnet first in VLSM to avoid waste","/30 subnets (2 usable hosts) are used for point-to-point links between routers","Practice: given a range, identify which subnet an IP belongs to","Exam tip: memorize /24 to /32 subnet sizes, hosts, and block sizes cold"],
    recall:["What is VLSM and why is it used?","What subnet mask is typically used for point-to-point router links?","In VLSM design, why should you allocate the largest subnet first?"]},
  { day:15, title:"Subnetting Part 3", phase:1, mins:47,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+15+subnetting+3",
    summary:["Subnetting practice: given an IP and mask, find network, broadcast, first/last host","Given requirements (X hosts, Y subnets), choose the minimum prefix length that satisfies both","Class B subnetting: interesting octet is the 3rd; block size based on 3rd octet of mask","Class A subnetting follows same rules but with much larger address spaces","Speed is critical  -  aim to subnet in under 90 seconds for exam conditions"],
    recall:["A company needs 50 subnets from 10.0.0.0/8 each with at least 200 hosts. What prefix length to use?","Given 172.16.0.0/20, how many subnets from /16 and how many hosts per subnet?","What is the broadcast address of 10.0.1.128/25?"]},
  // ── PHASE 1: VLANs/STP/EtherChannel (Days 16-23) ────────────────────────
  { day:16, title:"VLANs Part 1", phase:1, mins:44,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+16+VLANs",
    summary:["VLANs segment a switch into multiple broadcast domains","Each VLAN is a separate Layer 3 subnet by convention","Access ports carry traffic for a single VLAN  -  untagged","'switchport mode access' + 'switchport access vlan X' configures an access port","'show vlan brief' displays all VLANs and their assigned ports"],
    recall:["What command assigns an interface to VLAN 20 as an access port?","What is the difference between an access port and a trunk port?","What command shows all VLANs on a switch?"]},
  { day:17, title:"VLANs Part 2", phase:1, mins:48,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+17+VLANs+2",
    summary:["Trunk ports carry traffic for multiple VLANs using 802.1Q tagging","802.1Q inserts a 4-byte tag into the Ethernet frame with VLAN ID (12-bit, supports 4096 VLANs)","Native VLAN traffic is sent untagged on trunks  -  both sides must agree (default VLAN 1)","'show interfaces trunk' shows trunk ports, allowed VLANs, and native VLAN","Best practice: change native VLAN from 1 to unused VLAN for security"],
    recall:["What is the native VLAN and how is it treated on a trunk?","What command restricts a trunk to only carry VLANs 10, 20, 30?","What is 802.1Q tagging?"]},
  { day:18, title:"VLANs Part 3", phase:1, mins:52,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+18+VLANs+inter-VLAN+routing",
    summary:["Inter-VLAN routing requires a Layer 3 device  -  VLANs cannot route between each other alone","Router-on-a-stick: one physical link with subinterfaces, each tagged with a VLAN","Layer 3 switch: uses SVIs (Switch Virtual Interfaces)  -  more scalable and faster","SVI = virtual interface on a switch assigned an IP, acts as default gateway for that VLAN","'ip routing' must be enabled on L3 switch for SVIs to route between VLANs"],
    recall:["What are the two main methods of inter-VLAN routing?","What is a SVI and what command creates one?","What command enables routing on a Layer 3 switch?"]},
  { day:19, title:"DTP and VTP", phase:1, mins:38,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+19+DTP+VTP",
    summary:["DTP (Dynamic Trunking Protocol): Cisco proprietary, auto-negotiates trunks between switches","DTP modes: dynamic auto (passive), dynamic desirable (active), trunk, access","Security: disable DTP on access ports with 'switchport nonegotiate' to prevent trunk spoofing","VTP (VLAN Trunking Protocol): propagates VLAN database across switches  -  rarely used today","VTP can cause catastrophic VLAN deletions  -  most engineers disable it (transparent mode)"],
    recall:["What DTP mode combination fails to form a trunk?","Why is DTP considered a security risk?","What is VTP and why is it considered dangerous?"]},
  { day:20, title:"Spanning Tree Protocol Part 1", phase:1, mins:54,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+20+spanning+tree+protocol",
    summary:["STP prevents Layer 2 loops which cause broadcast storms and MAC table instability","Root bridge elected: lowest Bridge ID (Priority + MAC). Default priority 32768","STP port roles: Root Port (best to root), Designated Port (best on segment), Non-designated (blocked)","Path cost: 10Mbps=100, 100Mbps=19, 1Gbps=4, 10Gbps=2","Classic STP (802.1D) convergence = 30-50 seconds; RSTP (802.1w) = ~1-2 seconds"],
    recall:["How is the root bridge elected in STP?","What are the three STP port roles?","What is the path cost of a 1 Gbps link in STP?"]},
  { day:21, title:"Spanning Tree Protocol Part 2", phase:1, mins:49,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+21+spanning+tree+2",
    summary:["STP port states: Blocking (15s) -> Listening (15s) -> Learning (15s) -> Forwarding","PortFast skips listening/learning for access ports  -  connects immediately (no loops possible)","BPDU Guard shuts port if it receives a BPDU  -  protects against rogue switches on access ports","Root Guard prevents an external switch from becoming root bridge","'spanning-tree vlan 10 root primary' sets priority to win root bridge election"],
    recall:["What are the STP port states in order and how long does each last?","What is PortFast and when should it be enabled?","What does BPDU Guard do when it detects a BPDU?"]},
  { day:22, title:"Rapid Spanning Tree Protocol", phase:1, mins:46,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+22+rapid+spanning+tree+RSTP",
    summary:["RSTP (802.1w) converges in ~1-2 seconds vs 30-50 for classic STP","RSTP port roles: Root, Designated, Alternate (backup to root), Backup (backup to designated)","RSTP port states: Discarding, Learning, Forwarding (simpler than 802.1D)","RSTP uses proposal/agreement handshake for fast transition rather than timers","Cisco PVST+ runs per-VLAN STP; Rapid PVST+ runs per-VLAN RSTP  -  Cisco default"],
    recall:["What are the RSTP port states?","What are the RSTP port roles and how do they differ from STP roles?","Why does RSTP converge so much faster than classic STP?"]},
  { day:23, title:"EtherChannel", phase:1, mins:48,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+23+EtherChannel",
    summary:["EtherChannel bundles multiple physical links into one logical link  -  STP sees it as one link","PAgP (Cisco): auto + auto = no bundle; desirable + desirable or auto = bundle","LACP (802.3ad): passive + passive = no bundle; active + active or passive = bundle","All member ports must have identical speed, duplex, VLAN config  -  mismatch suspends bundle","'show etherchannel summary' shows bundle status; 'P' in flags = port in channel"],
    recall:["What are the PAgP modes and which combination fails to form a bundle?","What are the LACP modes?","What must be identical on all member ports in an EtherChannel?"]},
  // ── PHASE 2: SECURITY ─────────────────────────────────────────────────────
  { day:24, title:"Floating Static Routes", phase:1, mins:35,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+24+floating+static+routes",
    summary:["Floating static route = static route with higher AD than dynamic protocol  -  acts as backup","If primary dynamic route disappears, floating static becomes active","Example: 'ip route 0.0.0.0 0.0.0.0 203.0.113.2 120'  -  AD 120 loses to OSPF (110) but wins if OSPF fails","Used for WAN backup links when primary connection uses a routing protocol","Verify with 'show ip route'  -  floating route not shown when primary is active"],
    recall:["What makes a static route 'floating'?","If OSPF AD is 110, what AD would you set a floating static backup route to?","How do you verify a floating static route is installed vs active?"]},
  { day:25, title:"RIP and EIGRP (Overview)", phase:1, mins:42,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+25+RIP+EIGRP",
    summary:["RIP v2: distance-vector, max 15 hops, metric=hop count, updates every 30s, AD=120","EIGRP: Cisco-enhanced distance-vector, composite metric (bandwidth+delay), AD=90 internal/170 external","EIGRP uses DUAL algorithm to guarantee loop-free paths and fast convergence","Successor = best path; Feasible Successor = backup path already validated as loop-free","Both RIP and EIGRP are less common on CCNA exam than OSPF  -  know concepts and AD values"],
    recall:["What is the maximum hop count for RIPv2?","What is the AD of EIGRP internal vs external?","What is the difference between a Successor and Feasible Successor in EIGRP?"]},
  { day:26, title:"OSPF Part 1", phase:2, mins:58,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+26+OSPF+part+1",
    summary:["OSPF is link-state: each router builds complete topology map (LSDB) using LSAs","Dijkstra SPF algorithm calculates shortest path; metric = cost (ref BW / interface BW)","Default reference bandwidth = 100 Mbps  -  all links ≥ 1Gbps get cost 1, change with 'auto-cost reference-bandwidth 1000'","Router ID: manually set > highest loopback IP > highest physical interface IP","Neighbour requirements: same area, subnet, hello/dead timers, MTU, no duplicate RIDs"],
    recall:["What algorithm does OSPF use and what is its metric?","How is the OSPF Router ID selected?","Why should you change the default OSPF reference bandwidth?"]},
  { day:27, title:"OSPF Part 2", phase:2, mins:55,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+27+OSPF+part+2",
    summary:["OSPF neighbour states: Down, Init, 2-Way, ExStart, Exchange, Loading, Full","On broadcast networks: DR/BDR elected  -  highest priority (default 1) wins, tie = highest RID","Non-DR/BDR routers form Full adjacency only with DR/BDR  -  stay at 2-Way with each other","Passive interface: sends no hello packets, appears as stub network in OSPF (use on LAN-facing interfaces)","LSA Type 1 (Router), Type 2 (Network/DR), Type 3 (Summary/ABR)  -  know for CCNA"],
    recall:["List the OSPF neighbour states in order.","How is the DR elected on a broadcast network? What happens if you set priority to 0?","What does 'passive-interface' do in OSPF?"]},
  { day:28, title:"OSPF Part 3", phase:2, mins:51,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+28+OSPF+part+3",
    summary:["Multi-area OSPF: Area 0 is backbone, all other areas must connect to Area 0","ABR connects multiple areas; ASBR redistributes external routes into OSPF","'network x.x.x.x wildcard area X' activates OSPF on interfaces matching that range","Per-interface OSPF config: 'ip ospf PROCESS area AREA' under the interface (preferred)","'show ip ospf neighbor' shows neighbours and state; 'show ip ospf interface brief' shows cost and role"],
    recall:["What is the role of Area 0 in multi-area OSPF?","What is the difference between an ABR and an ASBR?","What command configures OSPF on an interface directly rather than using the 'network' command?"]},
  { day:29, title:"First Hop Redundancy Protocols", phase:2, mins:48,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+29+FHRP+HSRP",
    summary:["FHRPs provide a virtual IP shared between routers so hosts always have a reachable gateway","HSRP (Cisco): Active/Standby, virtual MAC 0000.0C07.ACxx, hello 3s/hold 10s","VRRP (RFC): Master/Backup, preempt on by default, open standard","GLBP (Cisco): up to 4 active forwarders, provides actual traffic load balancing","HSRP preempt is off by default  -  configure to ensure highest priority router becomes active after recovery"],
    recall:["What is the difference between HSRP Active and Standby roles?","Which FHRP actually load-balances traffic across multiple routers?","What does HSRP preempt do and why must you configure it?"]},
  { day:30, title:"TCP and UDP", phase:2, mins:44,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+30+TCP+UDP",
    summary:["TCP: connection-oriented (3-way handshake SYN/SYN-ACK/ACK), reliable, ordered, flow control","UDP: connectionless, unreliable, no handshake, low overhead  -  best for real-time (VoIP, video)","TCP uses windowing for flow control: receiver advertises available buffer space","TCP segments have sequence numbers for ordering and retransmission detection","Port numbers: well-known 0-1023, registered 1024-49151, ephemeral/dynamic 49152-65535"],
    recall:["Describe the TCP 3-way handshake.","Why is UDP preferred for VoIP traffic despite being unreliable?","What is TCP windowing?"]},
  { day:31, title:"IPv6 Part 1", phase:2, mins:52,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+31+IPv6",
    summary:["IPv6 = 128-bit address, 8 groups of 4 hex digits separated by colons","Shortening: remove leading zeros, replace one consecutive all-zero group with ::","IPv6 types: Global Unicast (2000::/3), Link-local (FE80::/10), Loopback (::1/128), Multicast (FF00::/8)","Link-local addresses are auto-configured on every IPv6 interface  -  required for NDP","'ipv6 unicast-routing' must be enabled on routers to route IPv6 packets"],
    recall:["What are the two rules for shortening IPv6 addresses?","What is a link-local address and what prefix does it use?","What command enables IPv6 routing on a Cisco router?"]},
  { day:32, title:"IPv6 Part 2", phase:2, mins:47,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+32+IPv6+part+2",
    summary:["EUI-64: auto-generate Interface ID from MAC  -  split MAC, insert FFFE, flip 7th bit","SLAAC (Stateless Address Autoconfiguration): host uses RA to learn prefix, generates own ID with EUI-64","NDP replaces ARP: Neighbor Solicitation (like ARP request), Neighbor Advertisement (like ARP reply)","Router Solicitation (RS) sent by hosts on startup; Router Advertisement (RA) sent by routers","DHCPv6: stateful (like IPv4 DHCP) or stateless (prefix from RA, options from DHCPv6)"],
    recall:["Describe the EUI-64 process for generating an IPv6 Interface ID from a MAC address.","How does SLAAC work?","What NDP messages replace ARP in IPv6?"]},
  { day:33, title:"IPv6 Part 3", phase:2, mins:43,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+33+IPv6+part+3",
    summary:["IPv6 static routes: 'ipv6 route PREFIX/LEN NEXT-HOP' or 'ipv6 route ::/0 NEXT-HOP' for default","IPv6 routing table: 'show ipv6 route'","OSPFv3 supports IPv6; configured under interface with 'ipv6 ospf PROCESS area AREA'","IPv6 multicast: FF02::1 (all nodes), FF02::2 (all routers), FF02::5 (OSPF all routers)","Solicited-node multicast: FF02::1:FF00:0/104  -  used by NDP for neighbour discovery"],
    recall:["What is the IPv6 default route command?","What multicast address do OSPFv3 routers use?","What is a solicited-node multicast address used for?"]},
  { day:34, title:"Standard ACLs", phase:2, mins:48,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+34+standard+ACLs",
    summary:["Standard ACLs match on source IP only  -  numbers 1-99, 1300-1999","Applied close to destination since they can't match destination IP","Implicit deny any at end  -  every ACL denies everything not explicitly permitted","Named ACLs allow editing of specific entries; numbered ACLs require full rewrite to modify","Wildcard mask: 0 = must match, 1 = ignore; 'host' = 0.0.0.0, 'any' = 255.255.255.255"],
    recall:["What does a standard ACL match on?","Where should standard ACLs be applied  -  close to source or destination?","What is the implicit rule at the end of every ACL?"]},
  { day:35, title:"Extended ACLs", phase:2, mins:54,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+35+extended+ACLs",
    summary:["Extended ACLs match source/dest IP, protocol, and port  -  numbers 100-199, 2000-2699","Applied close to source to drop traffic early and save bandwidth","'eq 80' matches port 80; 'gt 1023' > 1023; 'range 20 21' range; 'established' = TCP return traffic","Named extended ACLs: 'ip access-list extended NAME' then sequence-numbered entries","'show ip access-lists' shows hit counts per ACE  -  useful for troubleshooting"],
    recall:["What can an extended ACL match that a standard ACL cannot?","Where should extended ACLs be placed and why?","What does the 'established' keyword match?"]},
  { day:36, title:"CDP and LLDP", phase:2, mins:33,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+36+CDP+LLDP",
    summary:["CDP (Cisco Discovery Protocol): Layer 2, Cisco-proprietary, discovers neighbouring Cisco devices","CDP sends advertisements every 60s; holdtime 180s; disable for security on external-facing ports","LLDP (Link Layer Discovery Protocol): IEEE 802.1AB, open standard, works across vendors","'show cdp neighbors' shows connected devices; 'show cdp neighbors detail' shows IP addresses","CDP can reveal network topology to attackers  -  disable with 'no cdp run' or per-interface 'no cdp enable'"],
    recall:["What layer does CDP operate at?","What is the difference between CDP and LLDP?","Why should CDP be disabled on interfaces connected to external networks?"]},
  { day:37, title:"NTP", phase:2, mins:38,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+37+NTP",
    summary:["NTP synchronises device clocks  -  critical for logging, certificates, authentication","Stratum 0 = atomic clock; Stratum 1 = directly connected; each hop adds 1","'ntp server IP' configures upstream NTP server; 'ntp master STRATUM' makes device an NTP server","'show ntp status' shows sync status and stratum; 'show ntp associations' shows servers","NTP uses UDP port 123; max practical stratum = 15 (16 = unsynchronised)"],
    recall:["Why is accurate time important on network devices?","What is the stratum system in NTP?","What UDP port does NTP use?"]},
  { day:38, title:"DNS", phase:2, mins:35,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+38+DNS",
    summary:["DNS resolves hostnames to IP addresses  -  hierarchical: root -> TLD -> authoritative","A record = IPv4, AAAA record = IPv6, CNAME = alias, MX = mail, PTR = reverse lookup","'ip name-server x.x.x.x' configures DNS server on IOS; 'ip domain-name' sets default domain","'no ip domain-lookup' prevents IOS from doing DNS lookups on CLI typos (useful in lab)","DNS uses UDP port 53 for queries; TCP port 53 for zone transfers"],
    recall:["What DNS record type maps a hostname to an IPv4 address?","What DNS record type is used for reverse lookups?","What command prevents IOS from treating CLI typos as DNS queries?"]},
  { day:39, title:"DHCP", phase:2, mins:44,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+39+DHCP",
    summary:["DHCP DORA: Discover (broadcast) -> Offer -> Request -> Acknowledge","'ip dhcp excluded-address' reserves IPs for static assignment; 'ip dhcp pool' creates pool","DHCP relay: 'ip helper-address SERVER_IP' on router interface forwards broadcasts to DHCP server","'show ip dhcp binding' shows assigned leases; 'show ip dhcp conflict' shows conflicting IPs","DHCP uses UDP: client sends from port 68, server responds to port 67"],
    recall:["What are the four steps of DHCP DORA?","What command configures a DHCP relay on a router interface?","What UDP ports does DHCP use?"]},
  { day:40, title:"SNMP", phase:2, mins:40,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+40+SNMP",
    summary:["SNMP monitors and manages network devices: Manager (NMS) ↔ Agent (on device) ↔ MIB database","v1/v2c use community strings (cleartext); v3 adds auth (SHA) and encryption (AES)  -  use v3","Operations: GET (read value), SET (change value), TRAP (agent alerts manager, UDP 162)","INFORM = reliable TRAP  -  requires acknowledgement from NMS; TRAP is fire-and-forget","OID (Object Identifier) identifies specific values in the MIB; walk = read all OIDs in sequence"],
    recall:["What is the difference between a TRAP and an INFORM in SNMP?","Why should you use SNMPv3 instead of v2c?","What UDP port do SNMP traps use?"]},
  { day:41, title:"Syslog", phase:2, mins:36,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+41+syslog",
    summary:["Syslog sends log messages to a centralised server for storage and analysis","8 severity levels (0-7): 0=Emergency, 1=Alert, 2=Critical, 3=Error, 4=Warning, 5=Notice, 6=Info, 7=Debug","'logging trap LEVEL' sends messages of that level and below to syslog server","'logging buffered SIZE LEVEL' stores logs in device memory; 'show logging' displays them","'service timestamps log datetime msec' adds timestamps to log messages  -  always configure this"],
    recall:["List the 8 syslog severity levels from most to least severe.","What command sends syslog messages to a remote server?","What command adds timestamps to log messages?"]},
  { day:42, title:"SSH", phase:2, mins:39,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+42+SSH+cisco",
    summary:["SSH encrypts CLI management traffic  -  always use SSH instead of Telnet","Requirements: hostname, domain name, RSA key pair ('crypto key generate rsa modulus 2048')","'ip ssh version 2' forces SSHv2  -  more secure than SSHv1","'transport input ssh' on VTY lines restricts to SSH only  -  blocks Telnet","'login local' on VTY uses local username/password database for authentication"],
    recall:["What are the steps to enable SSH on a Cisco device?","What command forces SSHv2 only?","How do you restrict VTY lines to SSH and block Telnet?"]},
  { day:43, title:"FTP and TFTP", phase:2, mins:34,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+43+FTP+TFTP",
    summary:["TFTP: simple, UDP, no auth, no encryption  -  used for IOS upgrades in trusted networks","FTP: TCP, supports auth, active and passive modes, control port 21, data port 20 (active) or random (passive)","'copy tftp: flash:' uploads an IOS image from TFTP server to flash","FTP passive mode: client initiates both connections  -  useful through firewalls/NAT","SFTP/SCP = encrypted file transfer  -  use instead of FTP for security"],
    recall:["What transport protocol does TFTP use?","What ports does FTP use for control and data in active mode?","What is the difference between FTP active and passive mode?"]},
  { day:44, title:"NAT Part 1", phase:2, mins:47,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+44+NAT+part+1",
    summary:["NAT translates private IPs to public IPs  -  conserves IPv4 address space","Inside local = private IP before translation; Inside global = public IP after translation","Static NAT: one-to-one permanent mapping; Dynamic NAT: pool of public IPs, first-come","PAT (Port Address Translation / NAT overload): many-to-one using ports  -  most common","'ip nat inside' and 'ip nat outside' define which interfaces NAT applies to"],
    recall:["What are the four NAT address types (inside local, inside global, etc.)?","What is the difference between static NAT, dynamic NAT, and PAT?","What command enables PAT using a single interface IP?"]},
  { day:45, title:"NAT Part 2", phase:2, mins:43,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+45+NAT+part+2",
    summary:["'show ip nat translations' shows active translation table entries","'show ip nat statistics' shows hit counts and interface designations","'debug ip nat' shows real-time translations  -  use carefully (CPU intensive)","PAT tracks source port number to distinguish multiple internal hosts sharing one IP","NAT hairpinning: allows inside hosts to reach inside servers via their public IP  -  not default"],
    recall:["What command shows the NAT translation table?","How does PAT distinguish multiple connections from different internal hosts?","What is NAT hairpinning?"]},
  { day:46, title:"QoS Part 1", phase:2, mins:49,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+46+QoS+part+1",
    summary:["QoS manages bandwidth, delay, jitter, and loss for different traffic types","Voice requirements: one-way delay <150ms, jitter <30ms, loss <1%","Classification: identify traffic (by IP, protocol, port, DSCP, CoS)","Marking: tag traffic at edge  -  DSCP in IP header (6-bit, 0-63), CoS in 802.1Q tag (3-bit, 0-7)","Key DSCP values: EF=46 (voice), AF41=34 (video), CS6=48 (routing protocols), BE=0 (default)"],
    recall:["What are the voice traffic requirements for delay, jitter, and loss?","What is the difference between classification and marking in QoS?","What DSCP value is used for voice traffic?"]},
  { day:47, title:"QoS Part 2", phase:2, mins:46,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+47+QoS+part+2",
    summary:["Queuing: FIFO (no priority), WFQ (fairness by flow), CBWFQ (guaranteed bandwidth per class)","LLQ = CBWFQ + strict priority queue  -  voice goes in priority queue, never waits","Policing: drops or remarks traffic exceeding rate limit; Shaping: buffers excess (smoother)","Traffic shaping smooths bursty traffic  -  adds delay but no drops; used toward slow WAN links","Congestion Avoidance: WRED drops packets early based on DSCP to avoid tail-drop"],
    recall:["What is LLQ and why is it preferred for voice traffic?","What is the difference between policing and shaping?","What is WRED and what problem does it solve?"]},
  // ── PHASE 2: SECURITY ─────────────────────────────────────────────────────
  { day:48, title:"Security Fundamentals", phase:2, mins:51,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+48+security+fundamentals",
    summary:["CIA Triad: Confidentiality (encryption), Integrity (hashing), Availability (redundancy)","Attack types: DoS/DDoS, phishing, spear-phishing, MITM, social engineering, malware, SQL injection","Symmetric encryption (AES): same key both directions, fast; Asymmetric (RSA): public/private key pair","Hashing: one-way, verifies integrity  -  MD5 (broken), SHA-1 (weak), SHA-256 (current standard)","AAA: Authentication (who), Authorisation (what), Accounting (what did they do)"],
    recall:["What does the CIA triad stand for?","What is the difference between symmetric and asymmetric encryption?","Why is MD5 considered insecure for hashing?"]},
  { day:49, title:"Port Security", phase:2, mins:47,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+49+port+security",
    summary:["Port security limits which MAC addresses can use a switch port  -  prevents MAC flooding","Violation modes: shutdown (err-disable, most secure), restrict (drop+log), protect (drop silently)","'switchport port-security mac-address sticky' learns and saves current MACs as secure","'errdisable recovery cause psecure-violation' auto-recovers err-disabled ports after a timer","'show port-security interface Gi0/1' shows secure MACs, violation count, and mode"],
    recall:["What are the three port security violation modes and what does each do?","What does 'sticky' MAC learning do?","How do you recover an err-disabled port?"]},
  { day:50, title:"DHCP Snooping", phase:2, mins:42,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+50+DHCP+snooping",
    summary:["DHCP Snooping prevents rogue DHCP servers from assigning fake IPs to hosts","Trusted ports (uplinks to legitimate DHCP server) can receive DHCP offers","Untrusted ports (client-facing) can only send DISCOVER and REQUEST  -  offers are dropped","DHCP Snooping binding table records MAC, IP, port, VLAN  -  used by DAI","Rate-limit DHCP on untrusted ports: 'ip dhcp snooping limit rate 15'"],
    recall:["What attack does DHCP Snooping prevent?","What is the difference between trusted and untrusted ports in DHCP Snooping?","How does DHCP Snooping work with DAI?"]},
  { day:51, title:"Dynamic ARP Inspection", phase:2, mins:40,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+51+dynamic+ARP+inspection",
    summary:["DAI prevents ARP spoofing (MITM attacks) by validating ARP messages against DHCP snooping table","Trusted ports (uplinks) are not inspected; untrusted ports (access) are checked","ARP packet with IP/MAC pair not in DHCP snooping binding table is dropped","For static IPs: create ARP ACL mapping IP to MAC and apply with 'ip arp inspection filter'","'show ip arp inspection statistics' shows forwarded and dropped ARP counts per VLAN"],
    recall:["What attack does DAI prevent?","Where does DAI get its validation data from?","How do you handle static IP hosts with DAI (no DHCP binding exists)?"]},
  // ── PHASE 3: WIRELESS ─────────────────────────────────────────────────────
  { day:52, title:"LAN Architectures", phase:3, mins:38,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+52+LAN+architectures",
    summary:["2-tier (collapsed core): access switches connect directly to distribution layer  -  small networks","3-tier: access -> distribution -> core  -  scalable for large campus networks","Spine-leaf: modern data centre; every leaf connects to every spine, no leaf-to-leaf links","STP not needed in spine-leaf as there are no loops in the design","PoE (Power over Ethernet): 802.3af (15.4W), 802.3at (30W), 802.3bt (90W)  -  powers APs, IP phones"],
    recall:["What are the three tiers in a traditional campus LAN architecture?","What is the advantage of a spine-leaf architecture?","What IEEE standard defines PoE and how much power does each deliver?"]},
  { day:53, title:"WAN Architectures", phase:3, mins:41,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+53+WAN+architectures",
    summary:["WAN connects geographically separate networks  -  typically via a service provider","Leased lines: dedicated point-to-point, expensive but reliable; T1=1.544Mbps, E1=2.048Mbps","MPLS: service provider creates VPN  -  CE routers connect to PE routers, provider handles routing","Internet VPN: IPsec over internet  -  cheaper than leased lines, less predictable quality","SD-WAN: centralised control of WAN links  -  can mix MPLS, internet, LTE for cost/performance"],
    recall:["What is MPLS and how does it differ from a leased line?","What are the components of an internet-based VPN?","What advantage does SD-WAN offer over traditional WAN?"]},
  { day:54, title:"Virtualisation and Cloud Part 1", phase:3, mins:43,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+54+virtualisation+cloud",
    summary:["Hypervisor Type 1 (bare metal): runs directly on hardware  -  VMware ESXi, Hyper-V, KVM","Hypervisor Type 2 (hosted): runs on top of OS  -  VMware Workstation, VirtualBox","VMs share physical resources (CPU, RAM, storage) via hypervisor  -  each has own OS","vSwitch: software switch inside hypervisor connecting VMs  -  can handle VLANs and trunking","Containers (Docker): lighter than VMs, share host OS kernel, start in seconds"],
    recall:["What is the difference between a Type 1 and Type 2 hypervisor? Give examples.","What is a vSwitch?","How do containers differ from virtual machines?"]},
  { day:55, title:"Virtualisation and Cloud Part 2", phase:3, mins:39,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+55+cloud+computing",
    summary:["IaaS: provider manages hardware/hypervisor, you manage OS upward  -  AWS EC2, Azure VM","PaaS: provider manages OS/runtime, you manage application  -  Heroku, Google App Engine","SaaS: provider manages everything  -  Office 365, Salesforce, Gmail","Public cloud: shared, internet-accessible; Private: dedicated, org-controlled; Hybrid: both","Cloud benefits: on-demand scaling, pay-as-you-go, geographic distribution, no upfront capex"],
    recall:["What are the three cloud service models and what does each party manage?","What is the difference between public, private, and hybrid cloud?","What is meant by 'elasticity' in cloud computing?"]},
  { day:56, title:"Wireless Fundamentals", phase:3, mins:55,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+56+wireless+fundamentals",
    summary:["802.11 standards: a=5GHz/54Mbps, b=2.4GHz/11Mbps, g=2.4GHz/54Mbps, n=both/600Mbps, ac=5GHz/6.9Gbps, ax=all/9.6Gbps","2.4 GHz: longer range, more interference, 3 non-overlapping channels (1,6,11)","5 GHz: shorter range, less interference, many non-overlapping channels","SSID = network name; BSSID = AP's MAC; ESSID = same SSID across multiple APs (roaming)","CSMA/CA (Collision Avoidance) used in wireless  -  different from wired CSMA/CD"],
    recall:["What are the non-overlapping channels on the 2.4 GHz band?","What is the difference between SSID, BSSID, and ESSID?","Why does 5 GHz have better throughput but shorter range than 2.4 GHz?"]},
  { day:57, title:"Wireless Architectures", phase:3, mins:50,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+57+wireless+architectures",
    summary:["Autonomous APs: self-contained, independently configured  -  suitable for small deployments","WLC (Wireless LAN Controller): centralised management, config, and RF management","Lightweight APs: minimal intelligence, register to WLC via CAPWAP protocol","CAPWAP: UDP 5246 (control, encrypted), UDP 5247 (data)  -  tunnel between LAP and WLC","Local mode: all traffic tunnelled to WLC; FlexConnect mode: local forwarding at branch"],
    recall:["What is the purpose of CAPWAP and what ports does it use?","What is the difference between autonomous AP and lightweight AP?","What is FlexConnect mode and why is it useful for branch offices?"]},
  { day:58, title:"Wireless Security", phase:3, mins:53,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+58+wireless+security",
    summary:["WEP: broken, never use  -  RC4 cipher, static key, weak IV","WPA: TKIP, RC4-based, stopgap  -  still considered weak","WPA2: AES/CCMP  -  PSK for personal, 802.1X/RADIUS for Enterprise","WPA3: SAE replaces PSK (offline dictionary attack resistant), OWE for open networks","EAP-TLS: mutual certs (most secure); PEAP: server cert + user/pass tunnel (most common)"],
    recall:["What encryption does WPA2 use?","What is the difference between WPA2 Personal and WPA2 Enterprise?","What improvement does WPA3 SAE provide over WPA2 PSK?"]},
  { day:59, title:"Wireless Configuration", phase:3, mins:46,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+59+wireless+configuration+WLC",
    summary:["WLC GUI: create WLAN -> set SSID, interface/VLAN, security (WPA2/802.1X or PSK)","QoS profile on WLAN: Platinum (voice), Gold (video), Silver (best effort), Bronze","RADIUS server configured on WLC for 802.1X authentication","RF management: channel assignment, power control, band steering (push clients to 5GHz)","'show wlan summary' on WLC CLI shows all configured WLANs and status"],
    recall:["What are the steps to create a WLAN on a Cisco WLC?","What QoS profile should be applied to a voice WLAN?","What is band steering?"]},
  // ── PHASE 4: AUTOMATION ───────────────────────────────────────────────────
  { day:60, title:"Network Automation Part 1", phase:4, mins:47,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+60+network+automation",
    summary:["Traditional management: SSH to each device individually  -  slow, error-prone, doesn't scale","Automation benefits: speed, consistency, auditability, version control","Data formats: JSON (REST APIs), XML (NETCONF), YAML (Ansible playbooks)","JSON: key-value pairs, strings in double quotes, supports nested objects and arrays","YANG: data modelling language that defines what can be configured/monitored via NETCONF/RESTCONF"],
    recall:["What are three benefits of network automation over manual CLI management?","What data format is used with NETCONF? With REST APIs?","What is YANG used for?"]},
  { day:61, title:"Network Automation Part 2", phase:4, mins:44,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+61+network+automation+2",
    summary:["REST API: uses HTTP methods  -  GET(read), POST(create), PUT(replace), PATCH(update), DELETE","HTTP codes: 200 OK, 201 Created, 400 Bad Request, 401 Unauthorized, 404 Not Found","NETCONF: SSH transport (port 830), XML format, get-config/edit-config operations","RESTCONF: HTTP transport, JSON or XML, simplified REST equivalent of NETCONF","SDN: centralised control plane; northbound API (controller to apps), southbound (controller to devices)"],
    recall:["What HTTP methods map to CRUD operations?","What port does NETCONF use and what transport protocol?","What is the northbound API vs southbound API in SDN?"]},
  { day:62, title:"Ansible, Puppet, and Chef", phase:4, mins:39,
    url:"https://www.youtube.com/results?search_query=jeremy+it+lab+ccna+day+62+ansible+puppet+chef",
    summary:["Ansible: agentless, push-based, YAML playbooks, uses SSH  -  easiest to learn","Puppet: agent-based, pull-based, Puppet DSL manifests  -  good for large scale","Chef: agent-based, pull-based, Ruby DSL (recipes/cookbooks)  -  developer-focused","Idempotent: running the same automation multiple times produces the same result  -  no duplicates","Cisco DNA Centre (Catalyst Centre): GUI-based network automation and intent-based networking"],
    recall:["What is the key difference between Ansible and Puppet in terms of agent and direction?","What does 'idempotent' mean in the context of automation?","What language do Ansible playbooks use?"]},
];

export const COURSE_PHASES = {
  1: { label:"Consolidation & gap-fill", color:"#7c6df0" },
  2: { label:"Network security & routing", color:"#00c896" },
  3: { label:"Wireless & cloud", color:"#f59e0b" },
  4: { label:"Automation", color:"#f97316" },
};

export const TOTAL_VIDEOS = COURSE.length;